a = input('Digite algo: ')

print('qual é o seu tipo primitivo? ',type(a))
print('Só tem espaço? ',a.isspace())
print('É numérico? ',a.isnumeric())
print('É alfabético? ',a.isalpha())
print('É alfanumérico? ' ,a.isalnum())
print('Está em maiúsculas? ' ,a.isupper())
print('Está em minúsculas? ' ,a.islower())
print('Está capitalizada? ' ,a.istitle())
